config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sweets#index'
  resources :users, only: [:show, :index]
  resources :sweets, only: [:new, :create, :index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sweet.rb
class Sweet < ApplicationRecord
  belongs_to :user
  attachment :sweet_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :sweets, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sweets_controller.rb
class SweetsController < ApplicationController
  #おかし新規登録ページの表示
  def new
    @sweet = Sweet.new
  end
  #おかしの新規作成
  def create
    Sweet.create(sweet_params)
    #@sweet = Sweet.new(sweet_params)
    #@sweet.user_id = current_user.id
    #@sweet.save
    redirect_to sweets_path
  end
  def index
    @sweets = Sweet.all
  end
  def show
    @sweet = Sweet.find(params[:id])
  end

  private
    def sweet_params
      params.require(:sweet).permit(:name, :opinion, :sweet_image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
    @sweets = @user.sweets
  end
  def edit
    if @user = current_user
    else
       render :show
    end
  end
  def update
    @user = current_user
    if @user.update(user_params)
       redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sweets_helper.rb
module SweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Switter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="">
      <span class="">Switter</span>
      <ul class="">
        <% if user_signed_in? %>
          <li class="header">
            Favorite
          </li>
          <li class="header">
            About
          </li>
          <li class="header">
            <%= link_to "logout", destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li class="header">
            About
          </li>
          <li class="header">
            <%= link_to "Sign up", new_user_registration_path %>
          </li>
          <li class="header">
            <%= link_to "login", new_user_session_path %>
          </li>
        <% end %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/sweets/index.html.erb
<!-- カテゴリとランキングはrender -->


<!-- 一覧部分 -->
<h2>タイムライン</h2>
<table class="">
  <thead>
    <tr>
      <th class="">見出し１</th>
      <th class="">見出し２</th>
      <th class="">見出し３</th>
    </tr>
  </thead>
  <tbody>
    <% @sweets.each do |sweet| %>
    <tr>
      <td>
        <%= link_to sweet_path(sweet.id) do %>
          <%= sweet.name %>
        <% end %>
        </td>
      <td><%= sweet.opinion %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "＋", new_sweet_path %>

app/views/sweets/new.html.erb
<h2>おかし投稿</h2>
<%= form_for(@sweet, url: sweets_path) do |f| %>
  <div class="">
    <!-- f.label :name, "おかし名" -->
    <%= f.text_field :name, placeholder:"おかし名" %>
  </div>
  <div class="">
    <!-- f.label :opinion, "おかし説明" -->
    <%= f.text_area :opinion, placeholder:"おかし説明" %>
  </div>
  <div class="">
    <!-- f.attachment_field :sweet_image -->
  </div>
  <%= f.submit '登録' %>
<% end %>

app/views/sweets/show.html.erb
<h2><%= sweet.name %></h2>
<p><%= sweet.opinion %></p>
<%= attachment_image_tag @sweet, :image %>
<!-- 編集ボタン -->
<!-- 削除ボタン -->

app/views/users/edit.html.erb
<h2>編集画面</h2>
<%= form_for(@user) do |f| %>

app/views/users/index.html.erb
<h2>ユーザー一覧</h2>
<table class="">
  <thead>
    <tr>
      <th class="">見出し１</th>
      <th class="">見出し２</th>
      <th class="">見出し３</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td>
          <%= user.name %>
      </td>
      <td>
        <%= user.introduction %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>